# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/Project 4/Project 4.cache/wt} [current_project]
set_property parent.project_path {C:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/Project 4/Project 4.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/Project 4/Project 4.srcs/sources_1/new/alu.v}
  {C:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/Project 4/Project 4.srcs/sources_1/new/register_file.v}
  {C:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/Project 4/Project 4.srcs/sources_1/new/Processor_Components_Top.v}
  {C:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/Project 4/Project 4.srcs/sources_1/imports/new/DB_PED.v}
  {C:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/Project 4/Project 4.srcs/sources_1/imports/new/seven_segment.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/Project 4/Project 4.srcs/constrs_1/new/Processor_Components_Nexys_A7.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/Project 4/Project 4.srcs/constrs_1/new/Processor_Components_Nexys_A7.xdc}}]


synth_design -top Processor_Components_Top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Processor_Components_Top.dcp

catch { report_utilization -file Processor_Components_Top_utilization_synth.rpt -pb Processor_Components_Top_utilization_synth.pb }
