# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/oscar/Coding Projects/CSULB/CECS 361 FALL 2020/Lab 2/Lab 2.cache/wt} [current_project]
set_property parent.project_path {C:/Users/oscar/Coding Projects/CSULB/CECS 361 FALL 2020/Lab 2/Lab 2.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/oscar/Coding Projects/CSULB/CECS 361 FALL 2020/Lab 2/Lab 2.srcs/sources_1/imports/Downloads/CNF.v}
  {C:/Users/oscar/Coding Projects/CSULB/CECS 361 FALL 2020/Lab 2/Lab 2.srcs/sources_1/imports/Downloads/Solver.v}
  {C:/Users/oscar/Coding Projects/CSULB/CECS 361 FALL 2020/Lab 2/Lab 2.srcs/sources_1/new/top_level_mod.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/oscar/Coding Projects/CSULB/CECS 361 FALL 2020/Lab 2/Lab 2.srcs/constrs_1/imports/Downloads/NexysA7-100T-Lab2.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/oscar/Coding Projects/CSULB/CECS 361 FALL 2020/Lab 2/Lab 2.srcs/constrs_1/imports/Downloads/NexysA7-100T-Lab2.xdc}}]


synth_design -top top_level_mod -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top_level_mod.dcp

catch { report_utilization -file top_level_mod_utilization_synth.rpt -pb top_level_mod_utilization_synth.pb }
