# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/project_5/project_5.srcs/sources_1/ip/ipmemory/ipmemory.xci
# IP: The module: 'ipmemory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/project_5/project_5.srcs/sources_1/ip/ipmemory/ipmemory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ipmemory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/project_5/project_5.srcs/sources_1/ip/ipmemory/ipmemory.xci
# IP: The module: 'ipmemory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/project_5/project_5.srcs/sources_1/ip/ipmemory/ipmemory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ipmemory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
