# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/Project 3/Project 3.cache/wt} [current_project]
set_property parent.project_path {C:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/Project 3/Project 3.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/Project 3/Project 3.srcs/sources_1/imports/new/seven_segment.v}
  {C:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/Project 3/Project 3.srcs/sources_1/new/debounce_filter.v}
  {C:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/Project 3/Project 3.srcs/sources_1/new/posedge_check_output.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/Project 3/Project 3.srcs/constrs_1/new/debounce_test_Nexys_A7.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/Project 3/Project 3.srcs/constrs_1/new/debounce_test_Nexys_A7.xdc}}]


synth_design -top posedge_check_output -part xc7a100tcsg324-1


write_checkpoint -force -noxdef posedge_check_output.dcp

catch { report_utilization -file posedge_check_output_utilization_synth.rpt -pb posedge_check_output_utilization_synth.pb }
