# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/Project 1/Project 1.cache/wt} [current_project]
set_property parent.project_path {C:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/Project 1/Project 1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/Project 1/Project 1.srcs/sources_1/new/FA.v}
  {C:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/Project 1/Project 1.srcs/sources_1/new/FA4.v}
  {C:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/Project 1/Project 1.srcs/sources_1/new/FA8.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/Project 1/Project 1.srcs/constrs_1/new/FA8_Nexys_A7_100T.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/oscar/Coding Projects/CSULB/CECS 301 SPRING 2020/Project 1/Project 1.srcs/constrs_1/new/FA8_Nexys_A7_100T.xdc}}]


synth_design -top FA8 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef FA8.dcp

catch { report_utilization -file FA8_utilization_synth.rpt -pb FA8_utilization_synth.pb }
