# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/Coding Projects/CECS 201 FALL 2019/project_4_final/project_4_final.cache/wt} [current_project]
set_property parent.project_path {E:/Coding Projects/CECS 201 FALL 2019/project_4_final/project_4_final.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
read_verilog -library xil_defaultlib {{E:/Coding Projects/CECS 201 FALL 2019/project_4_final/project_4_final.srcs/sources_1/imports/project_4_files/mux_4to1_case.v}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{E:/Coding Projects/CECS 201 FALL 2019/project_4_final/project_4_final.srcs/constrs_1/new/mux_2to1_case_NexysA7-100T.xdc}}
set_property used_in_implementation false [get_files {{E:/Coding Projects/CECS 201 FALL 2019/project_4_final/project_4_final.srcs/constrs_1/new/mux_2to1_case_NexysA7-100T.xdc}}]

read_xdc {{E:/Coding Projects/CECS 201 FALL 2019/project_4_final/project_4_final.srcs/constrs_1/new/mux_4to1_case_NexysA7-100T.xdc}}
set_property used_in_implementation false [get_files {{E:/Coding Projects/CECS 201 FALL 2019/project_4_final/project_4_final.srcs/constrs_1/new/mux_4to1_case_NexysA7-100T.xdc}}]


synth_design -top mux_4to1_case -part xc7a100tcsg324-1


write_checkpoint -force -noxdef mux_4to1_case.dcp

catch { report_utilization -file mux_4to1_case_utilization_synth.rpt -pb mux_4to1_case_utilization_synth.pb }
