# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/Coding Projects/CECS 201 FALL 2019/project_7/project_7.cache/wt} [current_project]
set_property parent.project_path {E:/Coding Projects/CECS 201 FALL 2019/project_7/project_7.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
read_verilog -library xil_defaultlib {
  {E:/Coding Projects/CECS 201 FALL 2019/project_7/project_7.srcs/sources_1/new/multiplexor_16bit_2_to_1.v}
  {E:/Coding Projects/CECS 201 FALL 2019/project_7/project_7.srcs/sources_1/new/counter_32bit.v}
  {E:/Coding Projects/CECS 201 FALL 2019/project_7/project_7.srcs/sources_1/new/top_counter_32bit.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{E:/Coding Projects/CECS 201 FALL 2019/project_7/project_7.srcs/constrs_1/new/Nexys_A7_top_counter_32bit.xdc}}
set_property used_in_implementation false [get_files {{E:/Coding Projects/CECS 201 FALL 2019/project_7/project_7.srcs/constrs_1/new/Nexys_A7_top_counter_32bit.xdc}}]


synth_design -top top_counter_32bit -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top_counter_32bit.dcp

catch { report_utilization -file top_counter_32bit_utilization_synth.rpt -pb top_counter_32bit_utilization_synth.pb }
