# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/oscar/Coding Projects/CSULB/CECS 361 FALL 2020/Lab 4/Lab 4.cache/wt} [current_project]
set_property parent.project_path {C:/Users/oscar/Coding Projects/CSULB/CECS 361 FALL 2020/Lab 4/Lab 4.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/oscar/Coding Projects/CSULB/CECS 361 FALL 2020/Lab 4/Lab 4.srcs/sources_1/imports/Downloads/LShift_Reg_Clr.v}
  {C:/Users/oscar/Coding Projects/CSULB/CECS 361 FALL 2020/Lab 4/Lab 4.srcs/sources_1/new/FA_5bit.v}
  {C:/Users/oscar/Coding Projects/CSULB/CECS 361 FALL 2020/Lab 4/Lab 4.srcs/sources_1/new/Register.v}
  {C:/Users/oscar/Coding Projects/CSULB/CECS 361 FALL 2020/Lab 4/Lab 4.srcs/sources_1/imports/Downloads/LShift_Reg.v}
  {C:/Users/oscar/Coding Projects/CSULB/CECS 361 FALL 2020/Lab 4/Lab 4.srcs/sources_1/new/Counter.v}
  {C:/Users/oscar/Coding Projects/CSULB/CECS 361 FALL 2020/Lab 4/Lab 4.srcs/sources_1/new/FSM_try1.v}
  {C:/Users/oscar/Coding Projects/CSULB/CECS 361 FALL 2020/Lab 4/Lab 4.srcs/sources_1/new/Iter_Div.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/oscar/Coding Projects/CSULB/CECS 361 FALL 2020/Lab 4/Lab 4.srcs/constrs_1/imports/CECS 361 FALL 2020/Nexys-A7-100T-Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/oscar/Coding Projects/CSULB/CECS 361 FALL 2020/Lab 4/Lab 4.srcs/constrs_1/imports/CECS 361 FALL 2020/Nexys-A7-100T-Master.xdc}}]


synth_design -top Iter_Div -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Iter_Div.dcp

catch { report_utilization -file Iter_Div_utilization_synth.rpt -pb Iter_Div_utilization_synth.pb }
